package com.aimock.interview.entity;

public enum JobRole {
    JAVA_BACKEND_DEVELOPER,
    FULL_STACK_DEVELOPER,
    REACT_FRONTEND_DEVELOPER,
    DATA_STRUCTURES_AND_ALGORITHMS,
    PYTHON_DEVELOPER,
    DEVOPS_ENGINEER,
    SYSTEM_DESIGN_ENGINEER,
    DATABASE_ENGINEER,
    HR_GENERAL,
    BEHAVIORAL_LEADERSHIP
}
